name: Deploy Docker Image to EC2

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the Docker image from the Dockerfile in the repository
      - name: Build Docker image
        run: docker build -t rokstack-react-image .


      # Save the Docker image as a tar file to transfer it
      - name: Save Docker image as a tar file
        run: docker save rokstack-react-image > rokstack-react-image.tar

      # Configure AWS CLI with your AWS credentials
      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2' # Ensure this is set to your target AWS region
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      # Upload the Docker image tar file to an S3 bucket
      - name: Upload Docker image to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.DOCKER_S3_BUCKET_NAME }}
        run: aws s3 cp rokstack-react-image.tar s3://$DOCKER_S3_BUCKET_NAME/rokstack-react-image.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy Docker image to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_IP }} # Use the actual secret name for your EC2 instance's IP or DNS
          username: ${{ secrets.SSH_USERNAME }} # Use the actual secret name for your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Use the actual secret name for your SSH private key
          script: |
            # Ensure AWS CLI is installed
            if ! command -v aws &> /dev/null
            then
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install
            fi
            
            
            # Configure AWS CLI
            aws configure set default.region eu-west-2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} # Use the actual secret name for your AWS access key ID
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Use the actual secret name for your AWS secret access key

            # Pull the Docker image tar file from S3
            aws s3 cp s3://${{ secrets.DOCKER_S3_BUCKET_NAME }}/rokstack-react-image.tar rokstack-react-image.tar

            # Load the Docker image from the tar file
            docker load < rokstack-react-image.tar

            # Stop any running container named rokstack-react-container
            docker stop rokstack-react-container || true

            # Remove the stopped container
            
            docker rm rokstack-react-container || true

            # Run a new container from the loaded Docker image
            docker run -d -p 8080:80 --name rokstack-react-container rokstack-react-image



  
